### PR TITLE
3ds: added libiconv

### PR DESCRIPTION
**Pull request by tbeloqui**

### CODE REVIEW

**Comment by mtheall** [comment]
What's this needed for? This is a pretty heavy dependency, and it would be awkward to support the circular dependency between libiconv and gettext. If you only need utf8/utf16/utf32, libctru has lightweight conversion code for those.

**Comment by tbeloqui** [comment]
@mtheall thanks for the feedback. I initially added this one as it as dependency for glib (which is a work in progress port) but if libcrtu has conversion functions for this I might then relay on those rather than pulling up the dependency.

**Comment by WinterMute** [comment]
> @mtheall thanks for the feedback. I initially added this one as it as dependency for glib (which is a work in progress port) but if libcrtu has conversion functions for this I might then relay on those rather than pulling up the dependency.

Being honest glib is a pretty hefty dependency as well. What's the ultimate goal here? i.e. what is it you're intending to port that needs these things?

**Comment by tbeloqui** [comment]
Yes I understand that, so I am ok to close the PR if the community wont benefit from this. The ultimate goal is to port gstreamer.

**Pull request closed without merging**
