### PR TITLE
add MBEDTLS_CMAC_C

### PR DESCRIPTION
**Pull request by HookedBehemoth**
This is needed for running hactool on the switch so I'd appreciate it getting merged.

### CODE REVIEW

**Comment by fincs** [comment]
Hmm, why do you need to run hactool on the Switch? I thought that was a PC tool?

**Comment by HookedBehemoth** [comment]
turned it into a lib that can easily be deployed on the switch but it won't link without cipher_cmac

**Comment by fincs** [comment]
I mean, what's exactly that library going to be used for?

**Comment by HookedBehemoth** [comment]
I'll use it to validate nca's on console but having a lib opens it to anyone to do anything hactool can do.

**Comment by HookedBehemoth** [comment]
Only extracting the exact parts I need would make this unmaintainable.

**Pull request closed without merging**
