### PR TITLE
Update 3ds-mbedtls to 2.16.6.

### PR DESCRIPTION
**Pull request by rinsuki**

### CODE REVIEW

**Comment by carstene1ns** [comment]
Can you fix `description` and `url` too? :+1:

**Comment by mtheall** [comment]
Can you do the switch port as well?

**Comment by rinsuki** [comment]
@carstene1ns Fixed 👍

@mtheall sorry, I can't test on real machine because I don't have Switch CFW/Homebrew environment. If still good, I make a patch.

**Comment by carstene1ns** [comment]
Should be straightforward, the switch patch is small enough.

**Comment by rinsuki** [comment]
Created #137

**Comment by WinterMute** [comment]
And while you're tidying up in here may as well replace the config.h part of the patch with the script used to enable/disable features like we did for switch.

See https://github.com/devkitPro/pacman-packages/blob/master/switch/mbedtls/PKGBUILD#L26-L30

**Comment by rinsuki** [comment]
@WinterMute I did it! so can you review?

**Comment by WinterMute** [comment]
Nice job, thanks for doing this.

**Pull request merged**
