### PR TITLE
switch: add ntfs-3g

### PR DESCRIPTION
**Pull request by DarkMatterCore**
Based on the original PKGBUILD script + patch from the libusbhsfs repository, plus some extra modifications based on the PPC portlib.

References:

* https://github.com/devkitPro/docker/pull/28
* https://devkitpro.org/viewtopic.php?p=17868

### CODE REVIEW

**Comment by DarkMatterCore** [comment]
It seems like the package generated by this build script isn't getting fully populated. After running `pacman -S switch-ntfs-3g` and checking `/opt/devkitpro/portlibs/switch`, only the NTFS-3G license is getting installed.

I'll look into the issue.

**Comment by WinterMute** [comment]
Heh, I didn't check the package contents, sorry. The PKGBUILD was missing the install step & it looks like that bit of the patch I thought wasn't necessary probably was. I've rebuilt the package, should be fine now.

**Comment by DarkMatterCore** [comment]
> Heh, I didn't check the package contents, sorry. The PKGBUILD was missing the install step & it looks like that bit of the patch I thought wasn't necessary probably was. I've rebuilt the package, should be fine now.

Thanks! I appreciate it.

Btw, I also noticed we're not copying the `config.h` file that gets generated during the NTFS-3G build steps. I created an additional PR to address that: https://github.com/devkitPro/pacman-packages/pull/347

Hope that helps.

**Comment by averne** [comment]
@WinterMute Would you be accepting PKGBUILDs for libnfs and libsmb2 as well? I have those on my tree but never tried to upstream them, since the team's standing seemed to be that filesystem implementations should live in sysmodules.

In the case of libsmb2, there is also an [old PR](https://github.com/devkitPro/pacman-packages/pull/116) that went inactive since `readv` and `writev` are not provided by newlib. Atomicity can be achieved by just copying the data to a single buffer and sending that over. Not pretty of course but this is what [glibc does](https://github.com/bminor/glibc/blob/master/sysdeps/posix/readv.c).

**Pull request merged**
